version: '2.4'
services:
  icecompass-api-webservice:
    ports:
      - "80:5050"
  icecompass-api-rq-worker:
    command: ["venv/bin/rq", "worker", "-u", "redis://icecompass-redis-ro.1ulmmw.ng.0001.euc1.cache.amazonaws.com:6379/0", "iceranking-tasks"]