version: '2.4'
services:
  icecompass-api-webservice:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RDS_DB_NAME: "${RDS_DB_NAME}"
      RDS_HOSTNAME: "${RDS_HOSTNAME}"
      RDS_USERNAME: "${RDS_USERNAME}"
      RDS_PASSWORD: "${RDS_PASSWORD}"
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: "${SECRET_KEY}"
      MAIL_SERVER: "${MAIL_SERVER}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      ICETEST_RABBIT_HOST: "${ICETEST_RABBIT_HOST}"
      ICETEST_RABBIT_USER: "${ICETEST_RABBIT_USER}"
      ICETEST_RABBIT_PASSWORD: "${ICETEST_RABBIT_PASSWORD}"
      ICETEST_RABBIT_VHOST: "${ICETEST_RABBIT_VHOST}"
      SENTRY_DSN: "${SENTRY_DSN}"
    ports:
      - "80:5050"
    links:
      - redis
  icecompass-api-rq-worker:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RDS_DB_NAME: "${RDS_DB_NAME}"
      RDS_HOSTNAME: "${RDS_HOSTNAME}"
      RDS_USERNAME: "${RDS_USERNAME}"
      RDS_PASSWORD: "${RDS_PASSWORD}"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: "${SECRET_KEY}"
      MAIL_SERVER: "${MAIL_SERVER}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      ICETEST_RABBIT_HOST: "${ICETEST_RABBIT_HOST}"
      ICETEST_RABBIT_USER: "${ICETEST_RABBIT_USER}"
      ICETEST_RABBIT_PASSWORD: "${ICETEST_RABBIT_PASSWORD}"
      ICETEST_RABBIT_VHOST: "${ICETEST_RABBIT_VHOST}"
      SENTRY_DSN: "${SENTRY_DSN}"
    entrypoint: [./rq-worker.sh]
    links:
      - redis
  icetest-rabbitmq-listener:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RDS_DB_NAME: "${RDS_DB_NAME}"
      RDS_HOSTNAME: "${RDS_HOSTNAME}"
      RDS_USERNAME: "${RDS_USERNAME}"
      RDS_PASSWORD: "${RDS_PASSWORD}"
      REDIS_URL: "redis://redis:6379/0"
      SECRET_KEY: "${SECRET_KEY}"
      ICETEST_RABBIT_HOST: "${ICETEST_RABBIT_HOST}"
      ICETEST_RABBIT_USER: "${ICETEST_RABBIT_USER}"
      ICETEST_RABBIT_PASSWORD: "${ICETEST_RABBIT_PASSWORD}"
      ICETEST_RABBIT_VHOST: "${ICETEST_RABBIT_VHOST}"
      SENTRY_DSN: "${SENTRY_DSN}"
    entrypoint: [./rabbitmq-listener.sh]
    links:
      - redis
  redis:
    image: redis