"""remove feif_id as primary_key

Revision ID: 05c25542d7e6
Revises: 5e4bf621db8b
Create Date: 2019-12-13 10:08:10.758456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05c25542d7e6'
down_revision = '5e4bf621db8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'competition_ranking_association', 'competitions', ['competition_id'], ['id'])
    op.create_foreign_key(None, 'competition_ranking_association', 'rankinglists', ['rankinglist_id'], ['id'])
    op.alter_column('horses', 'feif_id',
               existing_type=mysql.VARCHAR(length=12),
               nullable=True)
    op.create_unique_constraint(None, 'horses', ['feif_id'])
    op.create_foreign_key(None, 'results', 'horses', ['horse_id'], ['id'])
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'results', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'horses', type_='unique')
    op.alter_column('horses', 'feif_id',
               existing_type=mysql.VARCHAR(length=12),
               nullable=False)
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    # ### end Alembic commands ###
