"""added error flag in tasks

Revision ID: 0d42fc9fbfc5
Revises: fc8560c81c99
Create Date: 2021-01-07 13:27:04.588667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d42fc9fbfc5'
down_revision = 'fc8560c81c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'error')
    # ### end Alembic commands ###
