"""add rider_id foreignkey on rankingresults

Revision ID: 17645b7c6ee4
Revises: c3132d3faae4
Create Date: 2021-12-01 20:17:07.134476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17645b7c6ee4'
down_revision = 'c3132d3faae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'results_cache', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results_cache', type_='foreignkey')
    # ### end Alembic commands ###
