"""change templates on router to strings

Revision ID: 1b26557a3830
Revises: 8226fdbdc022
Create Date: 2022-05-27 17:00:21.489491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b26557a3830'
down_revision = '8226fdbdc022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bigscreen_template_routes')
    op.add_column('bigscreen_routes', sa.Column('templates', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bigscreen_routes', '_templates')
    op.create_table('bigscreen_template_routes',
    sa.Column('route_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('template_name', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['bigscreen_routes.id'], name='bigscreen_template_routes_ibfk_1'),
    sa.PrimaryKeyConstraint('route_id', 'template_name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
