"""add mark type to test definition

Revision ID: 298cdc854188
Revises: 6036e6ce7aaa
Create Date: 2020-11-21 22:15:28.016119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298cdc854188'
down_revision = '6036e6ce7aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('mark_type', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'mark_type')
    # ### end Alembic commands ###
