"""connect users and persons

Revision ID: 3034d8d0e3c1
Revises: a22dafcf320a
Create Date: 2022-01-21 17:21:52.795778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3034d8d0e3c1'
down_revision = 'a22dafcf320a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persons', 'persons', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_column('persons', 'person_id')
    # ### end Alembic commands ###
