"""Add lookup_error flag to horses

Revision ID: 30432516f01f
Revises: cf0816f9d0a0
Create Date: 2021-03-07 13:40:00.909303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30432516f01f'
down_revision = 'cf0816f9d0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('lookup_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'lookup_error')
    # ### end Alembic commands ###
