"""rankinglist test definitions

Revision ID: 35f2038f6217
Revises: 6052509f48ce
Create Date: 2019-12-17 12:45:34.034906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35f2038f6217'
down_revision = '6052509f48ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankinglist_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testcode', sa.String(length=3), nullable=True),
    sa.Column('rankinglist_id', sa.Integer(), nullable=False),
    sa.Column('included_marks', sa.Integer(), nullable=True),
    sa.Column('order', sa.String(length=4), nullable=True),
    sa.Column('grouping', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['rankinglist_id'], ['rankinglists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'competition_ranking_association', 'rankinglists', ['rankinglist_id'], ['id'])
    op.create_foreign_key(None, 'competition_ranking_association', 'competitions', ['competition_id'], ['id'])
    op.drop_column('rankinglists', 'included_marks')
    op.create_foreign_key(None, 'results', 'horses', ['horse_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'results', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'competitions', ['competition_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.add_column('rankinglists', sa.Column('included_marks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    op.drop_table('rankinglist_tests')
    # ### end Alembic commands ###
