"""empty message

Revision ID: 4048cc369fa7
Revises: 3fc586d55d99
Create Date: 2019-12-12 09:10:13.196435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4048cc369fa7'
down_revision = '3fc586d55d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('isirank_id', sa.String(length=10), nullable=True),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_ranking_association',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('rankinglist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['rankinglist_id'], ['rankinglists.id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'rankinglist_id')
    )
    op.drop_column('rankinglists', 'allowed_tests')
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.add_column('rankinglists', sa.Column('allowed_tests', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.drop_table('competition_ranking_association')
    op.drop_table('competitions')
    # ### end Alembic commands ###
