"""added test section schema

Revision ID: 4401fd3b2673
Revises: ae104c01ba06
Create Date: 2022-02-25 21:05:06.242153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4401fd3b2673'
down_revision = 'ae104c01ba06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_sections',
    sa.Column('testcode', sa.String(length=5), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('testcode', 'section_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_sections')
    # ### end Alembic commands ###
