"""more rankinglist settings on test

Revision ID: 493acb26c0df
Revises: 71d5a94ac455
Create Date: 2019-12-17 14:33:39.886334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493acb26c0df'
down_revision = '71d5a94ac455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'competition_ranking_association', 'rankinglists', ['rankinglist_id'], ['id'])
    op.create_foreign_key(None, 'competition_ranking_association', 'competitions', ['competition_id'], ['id'])
    op.add_column('rankinglist_tests', sa.Column('min_mark', sa.Float(), nullable=True))
    op.add_column('rankinglist_tests', sa.Column('rounding_precision', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rankinglist_tests', 'rankinglists', ['rankinglist_id'], ['id'])
    op.create_foreign_key(None, 'results', 'horses', ['horse_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'results', 'tests', ['test_id'], ['id'])
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'competitions', ['competition_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'rankinglist_tests', type_='foreignkey')
    op.drop_column('rankinglist_tests', 'rounding_precision')
    op.drop_column('rankinglist_tests', 'min_mark')
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    op.drop_constraint(None, 'competition_ranking_association', type_='foreignkey')
    # ### end Alembic commands ###
