"""empty message

Revision ID: 51f11b331717
Revises: af41d9176476
Create Date: 2019-12-06 10:06:32.225249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f11b331717'
down_revision = 'af41d9176476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankinglists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listname', sa.String(length=250), nullable=True),
    sa.Column('shortname', sa.String(length=3), nullable=True),
    sa.Column('allowed_tests', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_table('rankinglists')
    # ### end Alembic commands ###
