"""added rankinglist to tasks

Revision ID: 6036e6ce7aaa
Revises: e29928394640
Create Date: 2020-11-16 23:46:13.043096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6036e6ce7aaa'
down_revision = 'e29928394640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('rankinglist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'rankinglists', ['rankinglist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'rankinglist_id')
    # ### end Alembic commands ###
