"""Change tasks to work with rankinglist tests

Revision ID: 665d18e875e9
Revises: 91e86031f915
Create Date: 2020-06-06 14:26:50.428429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665d18e875e9'
down_revision = '91e86031f915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('rankinglist_test_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'rankinglist_tests', ['rankinglist_test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'rankinglist_test_id')
    # ### end Alembic commands ###
