"""add next_run_at column to job

Revision ID: 7e3cb78dc021
Revises: 1124dcd0020b
Create Date: 2022-03-16 00:43:57.541218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3cb78dc021'
down_revision = '1124dcd0020b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'next_run_at')
    # ### end Alembic commands ###
