"""added timestamps to tasks

Revision ID: 88e1ef4aef95
Revises: 298cdc854188
Create Date: 2020-12-31 12:21:57.254012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e1ef4aef95'
down_revision = '298cdc854188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'started_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
