"""add screen role

Revision ID: 8d35237375e9
Revises: 4401fd3b2673
Create Date: 2022-02-27 23:27:18.330360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d35237375e9'
down_revision = '4401fd3b2673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('role', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screens', 'role')
    # ### end Alembic commands ###
