"""add include in ranking to test

Revision ID: 920564232d7a
Revises: e43238c5dc67
Create Date: 2021-12-01 22:17:47.811602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '920564232d7a'
down_revision = 'e43238c5dc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests_ranking_association', sa.Column('test_id', sa.Integer(), nullable=False))
    op.drop_constraint('tests_ranking_association_ibfk_1', 'tests_ranking_association', type_='foreignkey')
    op.create_foreign_key(None, 'tests_ranking_association', 'tests', ['test_id'], ['id'])
    op.drop_column('tests_ranking_association', 'competition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests_ranking_association', sa.Column('competition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tests_ranking_association', type_='foreignkey')
    op.create_foreign_key('tests_ranking_association_ibfk_1', 'tests_ranking_association', 'tests', ['competition_id'], ['id'])
    op.drop_column('tests_ranking_association', 'test_id')
    # ### end Alembic commands ###
