"""add client_id to bigscreen

Revision ID: 93d15e20b8aa
Revises: 7336c47f0558
Create Date: 2022-01-23 13:22:59.383945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d15e20b8aa'
down_revision = '7336c47f0558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('client_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screens', 'client_id')
    # ### end Alembic commands ###
