"""add competition user rights model

Revision ID: ad301fbdfe9e
Revises: b7254706e20a
Create Date: 2022-05-25 22:16:01.623770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad301fbdfe9e'
down_revision = 'b7254706e20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_access',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'user_id')
    )
    op.add_column('users', sa.Column('super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'super_user')
    op.drop_table('competition_access')
    # ### end Alembic commands ###
