"""empty message

Revision ID: af41d9176476
Revises: 44c16948b088
Create Date: 2019-10-03 10:36:08.695595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af41d9176476'
down_revision = '44c16948b088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=250), nullable=True),
    sa.Column('lastname', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('results', sa.Column('rider_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'results', 'riders', ['rider_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'rider_id')
    op.drop_table('riders')
    # ### end Alembic commands ###
