"""Added country to competition

Revision ID: b35dd2486034
Revises: f3eb1561906d
Create Date: 2021-01-23 14:34:37.636118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35dd2486034'
down_revision = 'f3eb1561906d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'country')
    # ### end Alembic commands ###
