"""add tables for managing screens

Revision ID: b54b8e2ccefa
Revises: dcff376e9948
Create Date: 2022-01-23 10:22:23.889838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54b8e2ccefa'
down_revision = 'dcff376e9948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('search_results',
    # sa.Column('search_string', sa.String(), nullable=True),
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('type', sa.NullType(), nullable=False),
    # sa.PrimaryKeyConstraint('id', 'type')
    # )
    op.create_table('screengroups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template', sa.String(length=50), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screen_group_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['screen_group_id'], ['screengroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screens')
    op.drop_table('screengroups')
    # op.drop_table('search_results')
    # ### end Alembic commands ###
