"""add screen root font size

Revision ID: b7254706e20a
Revises: d7f1059343cf
Create Date: 2022-04-07 21:01:11.804109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7254706e20a'
down_revision = 'd7f1059343cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screens', sa.Column('root_font_size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screens', 'root_font_size')
    # ### end Alembic commands ###
