"""add name to screengroups

Revision ID: bd8d86ce0fdb
Revises: 1de83a72447b
Create Date: 2022-02-02 21:06:55.646262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8d86ce0fdb'
down_revision = '1de83a72447b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screengroups', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screengroups', 'name')
    # ### end Alembic commands ###
