"""add wf-lookup-date

Revision ID: cf0816f9d0a0
Revises: b35dd2486034
Create Date: 2021-02-03 14:59:26.326877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0816f9d0a0'
down_revision = 'b35dd2486034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horses', sa.Column('last_lookup', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horses', 'last_lookup')
    # ### end Alembic commands ###
