"""add explicit rider and horse id on rankingresult

Revision ID: d2b6aca24fcf
Revises: 920564232d7a
Create Date: 2021-12-19 19:06:56.161438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b6aca24fcf'
down_revision = '920564232d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results_cache', sa.Column('horse_id', sa.Integer(), nullable=True))
    op.add_column('results_cache', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_results_cache_horse_id'), 'results_cache', ['horse_id'], unique=False)
    op.create_index(op.f('ix_results_cache_rider_id'), 'results_cache', ['rider_id'], unique=False)
    op.create_foreign_key(None, 'results_cache', 'riders', ['rider_id'], ['id'])
    op.create_foreign_key(None, 'results_cache', 'horses', ['horse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results_cache', type_='foreignkey')
    op.drop_constraint(None, 'results_cache', type_='foreignkey')
    op.drop_index(op.f('ix_results_cache_rider_id'), table_name='results_cache')
    op.drop_index(op.f('ix_results_cache_horse_id'), table_name='results_cache')
    op.drop_column('results_cache', 'rider_id')
    op.drop_column('results_cache', 'horse_id')
    # ### end Alembic commands ###
