"""added type column to marks

Revision ID: d6d97ed173b2
Revises: 37268177acac
Create Date: 2022-02-25 20:43:26.152200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d97ed173b2'
down_revision = '37268177acac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('flag_ok', sa.Boolean(), nullable=True))
    op.add_column('marks', sa.Column('type', sa.String(length=10), nullable=False))
    op.drop_column('marks', 'is_ok')
    op.drop_column('marks', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('time', mysql.FLOAT(), nullable=True))
    op.add_column('marks', sa.Column('is_ok', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('marks', 'type')
    op.drop_column('marks', 'flag_ok')
    # ### end Alembic commands ###
