"""change job to cron expr

Revision ID: d7f1059343cf
Revises: 7e3cb78dc021
Create Date: 2022-03-18 21:56:49.618310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7f1059343cf'
down_revision = '7e3cb78dc021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cron_expr', sa.String(length=50), nullable=True))
    op.drop_column('jobs', 'minute')
    op.drop_column('jobs', 'year')
    op.drop_column('jobs', 'day')
    op.drop_column('jobs', 'second')
    op.drop_column('jobs', 'month')
    op.drop_column('jobs', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('hour', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('second', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('day', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('minute', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'cron_expr')
    # ### end Alembic commands ###
