"""change person_id foreign key to users table

Revision ID: dcff376e9948
Revises: 3034d8d0e3c1
Create Date: 2022-01-21 17:23:08.880864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcff376e9948'
down_revision = '3034d8d0e3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('persons_ibfk_1', 'persons', type_='foreignkey')
    op.create_foreign_key(None, 'persons', 'users', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.create_foreign_key('persons_ibfk_1', 'persons', 'persons', ['person_id'], ['id'])
    # ### end Alembic commands ###
