"""cascade on delete rankinglist

Revision ID: f3eb1561906d
Revises: 0d42fc9fbfc5
Create Date: 2021-01-12 23:54:15.009911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3eb1561906d'
down_revision = '0d42fc9fbfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rankinglist_tests_ibfk_1', 'rankinglist_tests', type_='foreignkey')
    op.create_foreign_key(None, 'rankinglist_tests', 'rankinglists', ['rankinglist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_ibfk_2', 'task', type_='foreignkey')
    op.drop_constraint('task_ibfk_3', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'rankinglist_tests', ['rankinglist_test_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'rankinglists', ['rankinglist_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_3', 'task', 'rankinglists', ['rankinglist_id'], ['id'])
    op.create_foreign_key('task_ibfk_2', 'task', 'rankinglist_tests', ['rankinglist_test_id'], ['id'])
    op.drop_constraint(None, 'rankinglist_tests', type_='foreignkey')
    op.create_foreign_key('rankinglist_tests_ibfk_1', 'rankinglist_tests', 'rankinglists', ['rankinglist_id'], ['id'])
    # ### end Alembic commands ###
