"""added state to competition

Revision ID: fc8560c81c99
Revises: 9d50870398d7
Create Date: 2021-01-06 16:00:32.406877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8560c81c99'
down_revision = '9d50870398d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('state', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'state')
    # ### end Alembic commands ###
